### ISSUE TITLE
small addition to your text

### ISSUE THREAD

**Issue by victorwestmann** [jdhoek/inkscape-isometric-projection#1]
Thank you very much for this amazing tool. I tested it and it works flawlessly in Windows 7 64 bit. ;-)

I would just like to add, if possible, the following

Windows 32 bit > C:\Program Files (x86)\Inkscape\share\extensions\
Windows 64 bit > C:\Program Files\Inkscape\share\extensions\

If you don't want or don't agree it's fine as well. Thank you once more!

**Comment by jdhoek** [comment]
Thanks for providing the correct paths, I appreciate it. I've fixed the README accordingly.
