### ISSUE TITLE
inkscape version 1.1 problem

### ISSUE THREAD

**Issue by ramanganap** [jdhoek/inkscape-isometric-projection#11]
I downloaded and added isometric_projection.inx and .py file ti inkscape 1.1
The extension menu pops up but doe not do the transformation I get error.
Any way to resolve the problem

C:\Program Files\Inkscape\share\inkscape\extensions\isometric_projection.py:11: DeprecationWarning: inkex.localize was moved to inkex.localization.localize.
  inkex.localize()
C:\Program Files\Inkscape\share\inkscape\extensions\isometric_projection.py:78: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Program Files\Inkscape\share\inkscape\extensions\isometric_projection.py:82: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Program Files\Inkscape\share\inkscape\extensions\isometric_projection.py:198: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  effect.affect()
C:\Program Files\Inkscape\share\inkscape\extensions\isometric_projection.py:162: DeprecationWarning: Effect.selected is now a dict in the SvgDocumentElement class. Use `self.svg.selected`.
  if len(self.selected) == 0:
C:\Program Files\Inkscape\share\inkscape\extensions\isometric_projection.py:172: DeprecationWarning: Effect.selected is now a dict in the SvgDocumentElement class. Use `self.svg.selected`.
  for id, node in self.selected.items():
C:\Program Files\Inkscape\share\inkscape\extensions\isometric_projection.py:173: DeprecationWarning: simpletransform.computeBBox -> sum([node.bounding_box() for node in aList])
  bbox = computeBBox([node])
Traceback (most recent call last):
  File "C:\Program

**Comment by jdhoek** [comment]
Hello,

It looks like you might be using an old version of the extension. These problems were fixed two years ago with the move to Inkscape 1.0.

Did you get the newest ones?

* [isometric_projection.inx](https://raw.githubusercontent.com/jdhoek/inkscape-isometric-projection/master/isometric_projection.inx)
* [isometric_projection.py](https://raw.githubusercontent.com/jdhoek/inkscape-isometric-projection/master/isometric_projection.py)

To find the location of your Inscape's extension files, look in the preferences menu under **System** and the **User extension** path there.

**Comment by ramanganap** [comment]
Hi;
I have 1.1 version of inkscape.
Kindly help me with files isometric_projection.inx and  isometric_projection.py 
I will save into folder inkscape/share/inkscape/extension .
Regards
Raman

**Comment by jdhoek** [comment]
If you look in your `inkscape/share/inkscape/extension` folder, are the `isometric_projection` files still there? If so, please remove these old ones first. Then restart Inkscape, and confirm that the extension is now gone.

After this, save `isometric_projection.inx` and `isometric_projection.py` in that extensions folder. [You can download them here.](https://inkscape.org/gallery/item/17465/inkscape-isometric-projection-2.1.zip) Then restart Inkscape.

The extension should now be available and work.

**Comment by ramanganap** [comment]
HI;
Thanks a million, the download and steps to follow helped to get the extension working.
It is useful tool to convert 2d drawings of model to 3 d models.

Regards
Raman

**Comment by jdhoek** [comment]
Good to hear. Glad you find the extension useful.
