### ISSUE TITLE
Inkscape 1.2!

### ISSUE THREAD

**Issue by garbanzo-toast** [jdhoek/inkscape-isometric-projection#12]
Just want to say that I love this extension! Unfortunately, the move to Inkscape 1.2 has broken the extension...is there any chance the extension could be updated? Thanks again!

**Comment by garbanzo-toast** [comment]
I'm an idiot, updating inkscape wipes extensions

**Comment by jdhoek** [comment]
Thanks for reporting any way. :)

So the extension works in 1.2? Good to hear!
