### ISSUE TITLE
Isometric Projection get error under Debian 10 Buster with Inkscape 1.0.2

### ISSUE THREAD

**Issue by dreadful-itconsultant** [jdhoek/inkscape-isometric-projection#15]
Using inkscape 1.0.2 on debian 10 'buster'. When run this 3.0 extensions, get error. The older version 2.1 run no error.

Traceback (most recent call last):
  File "axonometric_projection.py", line 184, in <module>
    effect.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 140, in run
    self.save_raw(self.effect())
  File "axonometric_projection.py", line 164, in effect
    tr = transform @ effect_matrix
TypeError: unsupported operand type(s) for @: 'Transform' and 'Transform'

Best regards

**Comment by jdhoek** [comment]
I'm afraid that looks like a limitation in the API Inkscape `1.0.2` provides. The current version of Inkscape is `1.2.1`, I would recommend updating your Inkscape version if you can (it has lots of very nice improvements).

If you can't update Inkscape, you can use an older version of this extension. I think `v2.1` is indeed the latest you can run on Inkscape `1.0.2`.

Thanks for reporting this. I'll add a note to the README.
