### ISSUE TITLE
Problem @ symbol in python file

### ISSUE THREAD

**Issue by Julesghes** [jdhoek/inkscape-isometric-projection#16]
I have ubuntu 21.10, and I moved files .inx and .py in inkscape extention.

I restarted inkscape, and I launched isometric transformation, but I had an error on the 164 line of the axonometric_projection.py file.
So, i imported numpy and  I removed "tr = transform @ effect_matrix" with "tr =np.dot(transform, effect_matrix)" and it works.

I share my experience  

Previously, on my old laptop (unbutu 22.04 LTS), I enjoyed isometric transformation and I didn't need to do that, curious.
Thanks for your extention

**Comment by jdhoek** [comment]
This sounds like it could be issue #15. Which version of Inkscape are you using?

Also, Ubuntu 21.10 is an interim release, which means it is only [supported for a short period](https://ubuntu.com/about/release-cycle). Have you considered updating to Ubuntu 22.04 LTS?

**Comment by Julesghes** [comment]
Now, the extension does the job pretty well, since I removed @ operator. 
I don't need to updating

The version is :
Inkscape 1.1.2 (0a00cf5339, 2022-02-04)

**Comment by jdhoek** [comment]
Yeah, that's an older version. The last supported version of this extension for Inkscape `1.1.2` is [v2.1](../../tree/v2.1) (as noted in the README). You might want to consider getting Inkscape `1.2.2`, but if this works for you, that's fine too of course.
