### ISSUE TITLE
Does not work in Inkscape 0.92.3

### ISSUE THREAD

**Issue by wstaelens** [jdhoek/inkscape-isometric-projection#2]
This does not seem to work in Inkscape 0.92.3 (2405546, 2018-03-11)
x64 bit Windows 10 Pro.

**Comment by jdhoek** [comment]
Version 1.2 of this extension seems to work fine in Inkscape 0.92.4 on Ubuntu Linux. Could you describe the behaviour you are seeing?

**Comment by wstaelens** [comment]
inkscape 0.92.4 i see the extension.
but in inkscape 0.92.3 (windows store app) I don't see the extension in the menu.

**Comment by jdhoek** [comment]
@wstaelens I would expect that you can install extensions in any Inkscape installation, regardless of its installation source. This extension should work in any recent Inkscape release. I have tested it in 0.92.3 and 0.92.4.

See [the Inkscape documentation](https://inkscape.org/gallery/=extension/) for more information. *I don't have access to a computer with Microsoft Windows myself*, so I can't confirm.

You might be installing the extension in the wrong location. Do other extensions work?

You can try asking for help with the Windows App Store version of Inkscape here: https://inkscape.org/community/

**Comment by wstaelens** [comment]
for 0.92.3: I've seen the locations and extension seem to be in the folder. 
other extensions work.

anyway you can close this as it works now in 0.92.4! It is just a matter of time before the windows store app will be updated to 0.92.4 also.
