### ISSUE TITLE
slight glitch in top right corner

### ISSUE THREAD

**Issue by ComputingFroggy** [jdhoek/inkscape-isometric-projection#4]
Hi, 
great tool ... but there's a tiny glitch when drawing a bow.
I draw a square of 10x10, then duplicate it 3 times, then use the tool to generate the right, left, and top side. Then I assemble them, it looks good ... except that looking closely at the top side right corner, I could see the right side going a little bit too far.
I spend a few minutes adjusting it and now it looks good.

Thanks for a great tool, any way.

**Comment by jdhoek** [comment]
Apologies for not responding sooner. Is that issue still reproducible? I haven't seen it come up before.
