### ISSUE TITLE
Inkscape 1,0 RC

### ISSUE THREAD

**Issue by adambelis** [jdhoek/inkscape-isometric-projection#6]
Hi I got this message after installing the extension on Win 10 Inkscape 1.0

> isometric_projection.py:11: DeprecationWarning: inkex.localize was moved to inkex.localization.localize
  inkex.localize()
isometric_projection.py:78: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
isometric_projection.py:82: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
isometric_projection.py:198: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  effect.affect()
isometric_projection.py:162: DeprecationWarning: Effect.selected is now a dict in the svg. Use `self.svg.selected`.
  if len(self.selected) == 0:
isometric_projection.py:172: DeprecationWarning: Effect.selected is now a dict in the svg. Use `self.svg.selected`.
  for id, node in self.selected.items():
isometric_projection.py:173: DeprecationWarning: simpletransform.computeBBox -> sum([node.bounding_box() for node in aList])
  bbox = computeBBox([node])
Traceback (most recent call last):
  File "isometric_projection.py", line 198, in <module>
    effect.affect()
  File "C:\Program Files\Inkscape 1.0\share\inkscape\extensions\inkex\deprecated.py", line 180, in affect
    return self.run(args=args)
  File "C:\Program Files\Inkscape 1.0\share\inkscape\extensions\inkex\base.py", line 123, in run
    self.save_raw(self.effect())
  File "isometric_projection.py", line 174, in effect
    midpoint = self.getMidPoint(bbox, node)
  File "isometric_projection.py", line 119, in getMidPoint
    x = bbox[1] - (bbox[1] - bbox[0]) / 2
TypeError: 'BoundingBox' object is not subscriptable

**Comment by jdhoek** [comment]
Hello,

You are using an outdated version of this extension. These issues are part of the transition to Inkscape 1.0.

They have been fixed in the latest releases of this extension, available here:

https://github.com/jdhoek/inkscape-isometric-projection/releases/tag/2.1
